# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 30, 14 * * * # Run at 2:30 UTC everyday
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: dev
      conditional_step:
        description: Run multi-line script?
        required: true
        default: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!  Deploying to ${{ github.event.inputs.environment }}

      - name: Run a multi-line script
        if: github.event.inputs.conditional_step
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Last step diagnostics
        if: always()
        run: |
          pwd
          printenv | sort
          ls -R
